// <auto-generated />
using System;
using DeviceMonnitorAPI.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeviceMonnitorAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20210710065525_Migration03")]
    partial class Migration03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DataGuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Param")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DataGuid");

                    b.ToTable("DataAI");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DataGuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Param")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DataGuid");

                    b.ToTable("DataAO");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataDI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DataGuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Param")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DataGuid");

                    b.ToTable("DataDI");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataDO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DataGuid")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Param")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DataGuid");

                    b.ToTable("DataDO");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataMEATADATA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DataGuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Param")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("DataGuid");

                    b.ToTable("DataMEATADATA");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.Device", b =>
                {
                    b.Property<Guid>("DeviceGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeviceGuid")
                        .HasName("PK_Device");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DeviceConfig", b =>
                {
                    b.Property<Guid>("ConfGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Cadw")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Calm")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Cup")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("DO0")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DO1")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DO2")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DO3")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("DeviceGuid")
                        .HasColumnType("char(36)");

                    b.Property<int>("DownTime")
                        .HasColumnType("int");

                    b.Property<int>("EMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Ertime")
                        .HasColumnType("int");

                    b.Property<int>("LowVtime")
                        .HasColumnType("int");

                    b.Property<int>("Ontime")
                        .HasColumnType("int");

                    b.Property<int>("OverVtime")
                        .HasColumnType("int");

                    b.Property<int>("Overtime")
                        .HasColumnType("int");

                    b.Property<decimal>("UMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Wdw")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Wup")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ConfGuid");

                    b.HasIndex("DeviceGuid");

                    b.ToTable("DeviceConfig");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DeviceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeviceGuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGuid");

                    b.ToTable("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.User", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("EditedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TokenExpire")
                        .HasColumnType("date");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserGuid")
                        .HasName("PK_Users");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserGuid = new Guid("7ba64c1d-823e-4841-8287-ed440f8ab217"),
                            CreatedDate = new DateTime(2021, 7, 10, 11, 55, 24, 824, DateTimeKind.Local).AddTicks(3099),
                            EditedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Api",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "@p!Adm!n21U$er00222",
                            Role = "ApiAdmin",
                            TokenExpire = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "apiadmin"
                        },
                        new
                        {
                            UserGuid = new Guid("467e2276-1f12-44d5-8ce2-a43dba846802"),
                            CreatedDate = new DateTime(2021, 7, 10, 11, 55, 24, 824, DateTimeKind.Local).AddTicks(3495),
                            EditedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            Password = "@@dm!nU$er",
                            Role = "Admin",
                            TokenExpire = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.Property<Guid>("DevicesDeviceGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersUserGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("DevicesDeviceGuid", "UsersUserGuid");

                    b.HasIndex("UsersUserGuid");

                    b.ToTable("DeviceUser");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataAI", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.DeviceData", "DeviceData")
                        .WithMany("DataAIs")
                        .HasForeignKey("DataGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataAO", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.DeviceData", "DeviceData")
                        .WithMany("DataAOs")
                        .HasForeignKey("DataGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataDI", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.DeviceData", "DeviceData")
                        .WithMany("DataDIs")
                        .HasForeignKey("DataGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataDO", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.DeviceData", "DeviceData")
                        .WithMany("DataDOs")
                        .HasForeignKey("DataGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DataMEATADATA", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.DeviceData", "DeviceData")
                        .WithMany("DataMetadatas")
                        .HasForeignKey("DataGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DeviceConfig", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.Device", "Device")
                        .WithMany("DevicesConfig")
                        .HasForeignKey("DeviceGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DeviceData", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.Device", "Device")
                        .WithMany("DevicesData")
                        .HasForeignKey("DeviceGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.HasOne("DeviceMonnitorAPI.DBModels.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesDeviceGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeviceMonnitorAPI.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.Device", b =>
                {
                    b.Navigation("DevicesConfig");

                    b.Navigation("DevicesData");
                });

            modelBuilder.Entity("DeviceMonnitorAPI.DBModels.DeviceData", b =>
                {
                    b.Navigation("DataAIs");

                    b.Navigation("DataAOs");

                    b.Navigation("DataDIs");

                    b.Navigation("DataDOs");

                    b.Navigation("DataMetadatas");
                });
#pragma warning restore 612, 618
        }
    }
}
